# fly.toml app configuration file generated for robin-copilot on 2026-04-03T09:15:21-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'robin-copilot'
primary_region = 'dfw'

[build]

[env]
  NODE_ENV = 'production'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
